// src/components/navbar.tsx
import React from 'react';
import Logo from '../assets/logo.svg';
import './navbar-style.css';

const Navbar: React.FC = () => {
    return (
        <div className="navbar-wrapper">
            <div className="navbar">
                <div className="logo-container">
                    <img className="logo-image" id="logo-svg" src={Logo}/>
                </div>
                <ul className="link-container">
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                    <li>
                        <a href="#work">Work</a>
                    </li>
                    <li>
                        <a href="#experience">Experience</a>
                    </li>
                    <li>
                        <a href="#about">About</a>
                    </li>
                </ul>
            </div>
        </div>
    );
};

export default Navbar;

// src/app/navbar/navbar.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent implements OnInit{

  constructor() { }
  ngOnInit() {
  }
}

<div class="navbar-wrapper">
  <div class="navbar">
    <div class="logo-container">
      <img class="logo-image" id="logo-svg" src="assets/logo.svg">
    </div>
    <ul class="link-container">
      <li>
        <a href="#contact">Contact</a>
      </li>
      <li>
        <a href="#work">Work</a>
      </li>
      <li>
        <a href="#experience">Experience</a>
      </li>
      <li>
        <a href="#about">About</a>
      </li>
    </ul>
  </div>
</div>
